### ISSUE TITLE
rails 4

### ISSUE THREAD

**Issue by patie** [leikind/wice_grid#103]
hi,

what about ruby on rails 4 support ?

thanks for answer

**Comment by leikind** [comment]
Hi

I haven't had time to do it yet

**Comment by asgeo1** [comment]
I'm using wice_grid in Rails 4. It works pretty good so far.

The only issue I've had is that Rails 4 comes with Turbolinks turned on by default. With turbolinks you can't rely on the "document ready" jQuery event, you have to listen for "page:load" instead.

There probably needs to be a setting in wice_grid so it can be configured to listen to "page:load" rather than document.ready

**Comment by leikind** [comment]
That's great to hear. I expected more things not to work.

I assume that `page:load` is only fired by turbolinks when a page is ... hmm ... _reloaded_ via turbolinks, right? So if  I in addition to 

```
jQuery ->
  initWiceGrid()
```

( https://github.com/leikind/wice_grid/blob/rails3/vendor/assets/javascripts/wice_grid_init.js.coffee ) I trigger `initWiceGrid()` on `page:load`, it should be enough.

**Comment by asgeo1** [comment]
Yeah, that's it. It should be pretty safe to listen to both ready and page:load. That's what I've been doing so far:

```
$(document).on 'page:load ready', ->
  # do stuff
```

**Comment by markbao** [comment]
Where are you guys making this change? It doesn't seem like `initWiceGrid()` is available as a `window` global, and it's a pain to edit the vendor asset.

**Comment by leikind** [comment]
@markbao  Here https://github.com/leikind/wice_grid/blob/rails3/vendor/assets/javascripts/wice_grid_init.js.coffee

But no version has been published which fully supports Rails 4.

I have finally started working in this direction. Because of the changes to how AR treats conditions in `where` and the new `references()` I will be forced to change the API a bit.

**Comment by markbao** [comment]
Got it — but is there a specific way to change this if it is installed as a gem? Is it necessary to modify the local copy?

**Comment by leikind** [comment]
@markbao you clone wice_grid to a location in your application directory and then use something like `gem "wice_grid",  :path => 'vendor/wice_grid'` in your Gemfile

**Comment by markbao** [comment]
Got it, thanks!

**Comment by leikind** [comment]
Turns out that `sanitize_sql_for_conditions` in Rails 4.0.0 is broken thanks to this bug: https://github.com/rails/rails/commit/a6bc35c82cd58aac61608391f38fda4e034be0f7#diff-1

The bug is fixed, but it is not in Rails 4.0.0 :(

`sanitize_sql_for_conditions` is needed by WiceGrid

**Comment by markbao** [comment]
Hmm... I don't see `sanitize_sql_for_conditions` in the WiceGrid codebase. What does this affect?

**Comment by leikind** [comment]
It's `sanitize_sql` in the current version https://github.com/leikind/wice_grid/blob/rails3/lib/wice/wice_grid_misc.rb#L63

**Comment by leikind** [comment]
No version has been released yet, but beginning with this commit https://github.com/leikind/wice_grid/tree/works_with_rails4 WiceGrid works with Rails4 for the exception of one deprecation message, which will be fixed in future versions by changing and modernizing the API a bit. One can feel the age of the API, I think, it all started as a plugin for Rails 2.0 and Prototype.js, in a private subversion repository :-) ...

**Comment by leikind** [comment]
version 3.4.0

**Comment by leikind** [comment]
if you've installed 3.4.0, please upgrade to 3.4.1, 3.4.0 has a nasty bug :(
