### ISSUE TITLE
grid#column without a block does not work when model_class is present

### ISSUE THREAD

**Issue by xavier** [leikind/wice_grid#20]
Example:

```
class Person < ActiveRecord::Base
  belongs_to :company 
end
```

...
    @people_grid = initialize_grid(Person, :include => :company, ...)
...
    grid(@people_grid) do |g|
      g.column(:attribute_name => "name")  # will output Person#name
      g.column(:attribute_name => "name", :model_class => "Company")  # will output Person#name whereas company.name would be expected
    end

I have the feeling that this might be a tricky one to solve.  It's a totally non-blocking issue but it had to be put on the record. :)

**Comment by leikind** [comment]
Discussion:

Yuri: here it is
Yuri:       if block.nil?
        if ! options[:attribute_name].blank?
          block = lambda{|obj| obj.send(options[:attribute_name])}
        else
          raise WiceGridArgumentError.new(
            "Missing column block without attribute_name defined. You can only omit the block if attribute_name is present.")
        end
      end

Yuri: I don't know the association name
xavier: but indeed you need to map the model class to the association
Yuri: yes
xavier: wouldn't it actually be better to give the association name in the column() call instead of the model class?
Yuri: if the API was based on associations and association reflections....
xavier: you can get the class from the association proxy
Yuri: it is possible
xavier: well in any case it's not urgent, you can keep it postponed until the big Rails 3.0 ARel rewrite :D
Yuri: I wou;d prefer to do so, till the Rails 3.0 rewrite
