### ISSUE TITLE
Strange behavior of datetime picker

### ISSUE THREAD

**Issue by webchi** [leikind/wice_grid#285]
Using wice_grid in [smartadmin wrapbootstrap theame](https://wrapbootstrap.com/theme/smartadmin-responsive-webapp-WB0573SK0). When opening page with grid there is no icon of small calendar for date select. When again click on contacts_path link than 4 icons of them are appearing. If I continue to click on the link to the number of icons increasing uncontrollably.
Is it a bug? Or feature?
![11](https://cloud.githubusercontent.com/assets/27108/13784010/ae518cb8-eade-11e5-995d-1d42a16865ba.png)

**Comment by leikind** [comment]
If this happens with some theme then obviously something messes up with the way WiceGrid's CSS/JS work. Try removing that theme and see if the problem persists

**Comment by webchi** [comment]
> Try removing that theme and see if the problem persists

It's impossible. Better find out why wice_grid javascript not initialize on first boot of the page. And only work from second clicking.

**Comment by joelw** [comment]
I've found that this sort of thing happens if you call the initWiceGrid() function multiple times, which can happen once you start doing fancy things with reloading bits using Ajax and so on.

It would be possible to modify the function to detect if it has been run already.. I have hacked this up in my application by doing something like the following, which literally just checks to see if the jquery datepicker icon is present.

```
      if (($('.date-filter.wg-jquery-datepicker i').length > 0) || (document.readyState != "complete")) {
        return;
     } else {
        initWiceGrid();
     }
```

If you're not manually calling initWiceGrid() and it's getting triggered by WiceGrid's own loading function, it would be better to do something like add a new class variable that records whether it has been initiated already.

**Comment by nahy** [comment]
Why could wice_grid not initialize on first boot of the page? No events also binded to filter or reset icons. May be this is turbolink issue or something else?

**Comment by webchi** [comment]
Funny that the number of icons is stored until you go to other links and continue grow up when you get back to grid page. After refreshing by F5 all are dissapearing. 

Yep... problem in turbolinks. When turn them off then no new icons were generated.
