### ISSUE TITLE
.CSV export file in /tmp is sometimes erased before being sent, causing error

### ISSUE THREAD

**Issue by iva2k** [leikind/wice_grid#30]
First off, great plugin!

I noticed this error and did some digging. I have Rails 2.3.10 and Ruby 1.8 on Mac OS X Snow Leopard under Mongrel 1.1.5. Apparently due to sporadic garbage collection while doing .CSV export, the temporary file in /tmp is sometimes erased before being sent, causing error in send_file.

According to the documentation of Ruby Tempfile close method, "close(unlink_now=false)
Closes the file. If the optional flag is true, unlinks the file after closing.
If you don‘t explicitly unlink the temporary file, the removal will be delayed until the object is finalized." (http://ruby-doc.org/core/classes/Tempfile.html).

It is obvious from code inspection (in wice_grid_view_helpers.rd:grid_csv) that the object (spreadsheet) is finalized upon return, and the file has not been sent yet, thus, the file can be unlinked / deleted before send_file (or not, depending on Ruby's garbage collector mood).

**Comment by leikind** [comment]
Thanks for the compliment and the detailed explanation, will take a look at it asap.

**Comment by leikind** [comment]
I created a branch called csv_fix (http://github.com/leikind/wice_grid/commits/csv_fix) and there the problem should be gone. 
So, true, the implementation was rather naïve and the fix is to make the tempfile object live longer till the call to send_file. I cannot return the tempfile from the helper because there's a to_s call somewhere  in render_to_string (and views are for returning text anyway), so I just put a link to the tempfile from the main grid object (http://github.com/leikind/wice_grid/commit/3040e633496d3a537651fadb6e22348dfcd9aa2d).
If this fixes the problem, I will merge it into master.

**Comment by iva2k** [comment]
Great, thanks! I checked the branch code out and gave it a try - file downloads every time now, but it is empty. After the download, the file stays on the disk in tmp (/var/folders/... on Mac OS), and the contents is there. If I put a breakpoint on the send_file and check file on disk - it is empty.

I think the file needs to be flushed or maybe even closed. Maybe you can still do spreadsheet.close before returning the path that feeds into send_file, and the garbage collection will not remove it until there is a spreadsheet or csv_tempfile object.

**Comment by iva2k** [comment]
I tried few changes to csv_fix, and this seems to work properly:

```
    ...
    grid.csv_tempfile.close
    send_file temp_filename, :filename => filename, :type => 'text/csv'
    grid.csv_tempfile = nil
```

**Comment by leikind** [comment]
committed and merged into master: http://github.com/leikind/wice_grid/commit/b93544352cbde6771b7b26389690997fda892610
Thanks!
