### ISSUE TITLE
CSV export is not using filters

### ISSUE THREAD

**Issue by jpemberthy** [leikind/wice_grid#37]
Yo!!, 1st I'd like to say thanks for this awesome plugin.

Currently I'm migrating from an older version of the plugin (prototype based) to the latest one using jQuery, almost everything is working fine but I'm having a weird issue while trying to export a csv file, it seems like it's skipping the filter, If I try to export a csv file from the current filtered result, the csv is being generated with the initial records instead of the filtered ones :(. Any Idea why this is happening? This is how one of my actions looks now:

<pre>
def index
  @transports = initialize_grid(Transport, 
    :include => [:survey, :pickup, :client, {:dropoff => :company}],
    :conditions => "surveys.transport_id IS NULL",
    :enable_export_to_csv => true,
    :per_page => 30,
    :csv_file_name => 'transports'
  )
  export_grid_if_requested(:grid => "transports_grid")
end
</pre>

Any help would be appreciated, thanks!

**Comment by leikind** [comment]
Hello,
Could you please post the view code, or at least a subset of the code where this problem is reproducible?

**Comment by jpemberthy** [comment]
Hey thanks for your answer, sure here it is:

The grid code used in index.html.erb

http://gist.github.com/622998

An this is the grid code used in _transports_grid.html.erb

http://gist.github.com/623000

thanks in advance!

**Comment by leikind** [comment]
Your template  _transports_grid.html.erb does not have definitions of columns, so when CSV is requested there is just no way that WiceGrid can initialize filters, process HTTP parameters and create the correct query to get the records. That's why you get all records.

You should have one and the same template for HTML and CSV. Take a look at how the example is organized:
http://github.com/leikind/wice_grid_examples/blob/master/app/controllers/csv_export_controller.rb
http://github.com/leikind/wice_grid_examples/tree/master/app/views/csv_export/

**Comment by jpemberthy** [comment]
Ah!! ok I'm gonna try this later today, I think I'll have to refactor all my grid templates to work as one using these (new for me) filters, thanks for your answer & for the plugin! great work.

**Comment by leikind** [comment]
Ok, let me know if you run into problems

**Comment by leikind** [comment]
Updated the online examples to the latest commit - http://grid.leikind.org/csv_export , click on View code

**Comment by jpemberthy** [comment]
Thanks!! I'll let you know if I get some problems (but I don't think so).

**Comment by leikind** [comment]
closing
