### ISSUE TITLE
run 'rails g wice_grid:install', but no js file be created

### ISSUE THREAD

**Issue by khakistone** [leikind/wice_grid#70]
wice_grid 3.2.0.pre1

$ rails g wice_grid:install
      create  config/initializers/wice_grid_config.rb
      create  config/locales/wice_grid.yml
      create  app/assets/stylesheets/wice_grid.css

**Comment by leikind** [comment]
True, because this versions uses the asset pipeline and the javascript files and images are inside the gem. You just have to require it in your application.js:  https://github.com/leikind/wice_grid_testbed/blob/master/app/assets/javascripts/application.js

This version is under development, that's why no gem has been released

**Comment by khakistone** [comment]
Got it, thank you very much!
