### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by fillipenorton** [leikind/wice_grid#72]
Hey Yuri,

I have one question for u, that i've tryed many ways to solve this, but i had not success

After update to branch rails3, i didn't get load the calendar_view_month.png

In my initializers/wice_grid_config.rb, is like this:

  # Icon to popup the calendar.
  Wice::Defaults::CALENDAR_ICON = "/assets/icons/grid/calendar_view_month.png"

and the image is there!

but i identify some problem

<img class="ui-datepicker-trigger" src="/assets/icons/grid/calendar_view_month.png" alt="De" title="De">

I saw the javascript did not appending this tag above

How can i do to solve that ?

Thanks so much!

**Comment by leikind** [comment]
I am not sure I understand what the problem is.

If you are using the latest code on github, all javascript has been made unobtrusive and taken out from the HTML page to separate coffeescript files.

The code responsible for triggering and creating jquery datepickers is here https://github.com/leikind/wice_grid/blob/rails3/vendor/assets/javascripts/wice_grid_init.js.coffee#L46

If you are using a released version, please let me know which.
