### ISSUE TITLE
Don't get this to work with SLIM

### ISSUE THREAD

**Issue by jmuheim** [leikind/wice_grid#78]
Hey there

Your gem looks really promising, but I can't get it to work with SLIM templating engine, while with HAML it works.

When having a SLIM template like this:

``` erb
h1 Listing positions

== grid(@positions_grid, class: 'table table-striped') do |g|
  - g.column name: 'Project' do |position|
    |This is a row
```

...wice_grid miraculously include the whole template in every column! See this screenshot:

![screen](https://www.evernote.com/shard/s42/sh/222c291c-6d7e-4613-923d-b3504a1df70a/1af6ebb2c3a59e85f9db883f0957ad61/res/3adbedf1-992d-4c0c-a687-760471972427/skitch.png?resizeSmall&width=832)

It would be really nice if this would work with SLIM. Maybe it's a problem of SLIM, I will create a ticket on their GitHub page, too: https://github.com/stonean/slim/issues/322.

Thanks!

**Comment by leikind** [comment]
I've never used slim, and though I do use HAML, I never put grid helpers into HAML, because if you think about it, it is one big helper, one big method call, and any HAML or slim markup here is unnecessary noise. The suggested way is placing grid code into helpers or dedicated erb partials: https://github.com/leikind/wice_grid_testbed/tree/master/app/views/custom_ordering

**Comment by jmuheim** [comment]
Thank you. But what about when just displaying a single value in the column's field is not enough? For example, I'd like to display a dropdown menu with links to actions (show, edit, destroy) in the last field of every column which involves a lot of HTML code. How'd you do that?

**Comment by jmuheim** [comment]
(By the way, you SHOULD use SLIM, it's much more beautiful than HAML imho).

**Comment by leikind** [comment]
I use content_tag(:div, my_content, :class => '') or standard Rails helpers, select_tag, etc. In the past WiceGrid had a so called ERB-style, when instead of one chunk like <%= grid() %> (or = grid()  ) you could write like this:

```
<% d.column ....  do |record|%>
   html goes here
   <%= rec.name%>
<% end %>
```

but it was deprecated and then thrown away, as no one used it, and in general it promoted bad style imho

**Comment by jmuheim** [comment]
What a pitty. :-1: 

But using partials I can do it like that:

``` slim
== grid(@positions_grid, class: 'table table-striped') do |g|
  - g.column name: 'ID', attribute: 'id', filter: false
  - g.column name: 'Project', attribute: 'name', model: 'Project' do |position| render('project_name_column', position: position) end
  - g.column name: 'Name', attribute: 'name' do |position| render('position_name_column', position: position) end
```

Still, it would be much nicer if I didn't have to create a partial for every such column.

**Comment by zedtux** [comment]
@leikind do you plan any fix for this issue ?

**Comment by leikind** [comment]
No

**Comment by zedtux** [comment]
In case I would be able to fix it, would you accept a PR ?

**Comment by leikind** [comment]
yes

**Comment by zedtux** [comment]
@leikind I'm trying to get the tests passing on the testbed repo, can you check my issue https://github.com/leikind/wice_grid_testbed/issues/4 please ?

**Comment by zedtux** [comment]
@leikind which branch should I use as origin for my branch ?

**Comment by leikind** [comment]
rails3

**Comment by zedtux** [comment]
Alright, thank you.
