### ISSUE TITLE
Numeric filter with single text field

### ISSUE THREAD

**Issue by ahmad-hussain-confiz** [leikind/wice_grid#79]
Is it possible to filter a numerical column with the exact value using a single text field instead a range?

**Comment by leikind** [comment]
Not in the present version of the plugin, but in a development branch I did some work on decoupling filter code into modules of their own in order to simplify coding custom filters, and the direct integer equality filter is  supposed to be added as a proof-of-concept of this decoupling. In other words, it'll be in version 3.2.1

**Comment by ahmad-hussain-confiz** [comment]
thanks

**Comment by leikind** [comment]
added in 3.2.1.
read the changelog http://leikind.org/wice_grid321pre1/
