### ISSUE TITLE
CSV Export, uninitialized constant CSV::Writer

### ISSUE THREAD

**Issue by Seaborg** [leikind/wice_grid#98]
I've tried to follow documentation, think I'm doing all ok still getting: uninitialized constant CSV::Writer
my controller:

``` ruby
def index
    @subjects_grid = initialize_grid(Subject, 
      :name => 'g1',
      :enable_export_to_csv => true,
      :csv_file_name => 'register' )
    export_grid_if_requested('g1' => 'csv_export/subjects_grid')
  end

csv_export/_subjects_grid.html.erb
<%= grid(@subjects_grid, hide_csv_button: true) do |g|

  g.column :name => 'ID', :attribute => 'subjectid' do |subject|
    subject.subjectid
  end

  g.column :name => 'Gender', :model => 'Sex', :attribute => 'gender', custom_filter: {'Male' => 'Male', 'Female' => 'Female', 'NOT DEFINED' => 'null'} do |subject|
    subject.sex.gender if subject.sex
  end
end %>
```

I'm on ruby 2.0.0-p0 and wice_grid '3.2.0.pre4' am I  missing something? I also tried to add: require 'csv', but still no go.

**Comment by leikind** [comment]
I will try running it under Ruby 2.0. Meanwhile upgrade to version 3.2.1 and let me know if it solves the problem

**Comment by Seaborg** [comment]
Tried 3.2.1, still the same: uninitialized constant CSV::Writer

**Comment by leikind** [comment]
Right, that was a bug and it is fixed in this commit: https://github.com/leikind/wice_grid/commit/c5cecf1b994490757aa431e4ce4eef6938a34653

Until this is not packaged as a version, you might want to get the latest sources from github manually or via a git submodule, and replace 

`gem "wice_grid",  'version'`

in your Gemfile by

`gem "wice_grid",  :path => 'vendor/wice_grid'`

Thanks for reporting it
